---
- name: House Keeping old FTP'd files
  hosts: [ftp_server]

    
  tasks:
    - name: Find Log LogFiles
      tags: always
      win_find:
        paths: C:\Temp\Incoming
        age: -1h
        age_stamp: ctime
        #patterns: "{{filepattern}}"
        #recurse: yes
      register: filestoremove

    - name: list of files to be removed
      tags: always
      vars:
        files: "{{ filestoremove.files | json_query('[].path') }}"
      debug: var=files
      when: filestoremove.matched > 0