---
- name: Check for files in errors directory on Dimensioners and reprocess
  hosts: [dimensioners]
  #become: yes

  tasks:
    # before processing, ensure todays failures file exist
    - name: create the base csv file
      lineinfile:
        dest: /opt/saia_flow/failure_data/{{ ansible_date_time.date }}_failure.csv
        line: "dimensioner,file,timestamp"
        create: yes

    - name: find files in the /opt/saia_flow/errors/ directory
      find:
        paths: /opt/saia_flow/errors/
        file_type: file
      register: errorFiles2Reprocess

    - name: write the error facts to the output csv file
      lineinfile:
        dest: "/opt/saia_flow/failure_data/{{ ansible_date_time.date }}_failure.csv"
        line: "{{  hostvars[inventory_hostname].inventory_hostname }},{{ item.path | basename }},{{ '%Y-%m-%d %H:%M:%S' | strftime(item.ctime) }}"
      with_items: "{{ errorFiles2Reprocess.files }}"
