---
- name: Check for files in errors directory on Dimensioners and reprocess
  hosts: [dimensioners]
  #become: yes

  tasks:
    # before processing, ensure todays error file exist
    - name: create the base csv file
      lineinfile:
        dest: /opt/saia_flow/errors/{{ ansible_date_time.date }}_errors.csv
        line: "dimensioner,file,timestamp"
        create: yes

    - name: find files in the /opt/saia_flow/errors/ directory
      find:
        paths: /opt/saia_flow/errors/
        file_type: file
      register: errorFiles2Reprocess
      
    - name: print errorFiles2Reprocess
      debug:
        var: errorFiles2Reprocess

    - name: write the error facts to the output csv file
      lineinfile:
        dest: /etc/netbox/netboxImport.csv
        line: "{{  hostvars[inventory_hostname].inventory_hostname }},{{ item[].path | basename }},{{ '%Y-%m-%d %H:%M:%S' | strftime(item[].ctime) }}"
      with_items: errorFiles2Reprocess.files

    - name: failures found
      fail:
        msg: "There 1 or more error files to be reprocessed on {{ ansible_host }}."
      when: errorFiles2Reprocess.matched > 0