---
# default variables file for saia-flow

# influxbd
influxdb_token: aoWOrJjPawxYWj_x3QAQVX2AzAH6Bn9ev2M74yGFvn-vRJZcElsVCUCp7YnX7UJsGwyleYwkSGsMtibcKhPkkw==
influxdb_url: http://100.64.47.154:8086/api/v2/write

# file system directories
rclone_dir: /root/.config/rclone/
base_dir: /opt/saia_flow
incoming_dir: /opt/saia_flow/incoming/
processed_dir: /opt/saia_flow/processed/
errors_dir: /opt/saia_flow/errors/
failures_dir: /opt/saia_flow/failure_data/

directory_list:
  - "{{ rclone_dir }}"
  - "{{ base_dir }}"
  - "{{ incoming_dir }}"
  - "{{ processed_dir }}"
  - "{{ errors_dir }}"

# scripts
watch_incoming_sh: "{{ base_dir }}/watch-incoming.sh"
influxdb_sh: "{{ base_dir }}/post2InfluxDB.sh"

# packages to deploy
package_list:
    - vsftpd
    - inotify-tools
    - rclone
    - openssl
    - ssl-cert

# rclone FTP server
ftp_host: dimftp.saia.com
ftp_user: anonymous
ftp_port: 21
ftp_pass: UesMorw2iw3iFJLB
ftp_tls: false
ftp_concurrency: 0
ftp_no_check_certificate: true
#remote:/dimensioner/